# specify which database and adapter to use for which environment

development:
  adapter: postgresql
  database: rush-hour-development

test:
  adapter: postgresql
  database: rush-hour-test

production:
  adapter: postgresql
  database: rush-hour-production
